# run and create release
name: release

on:
  workflow_dispatch:

jobs:
  release:
    if: (github.event.commits[0].author.name != 'github-actions') && (github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - name: View author
      run: echo "${{ github.event.commits[0].author.name }} ."

    - uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
        persist-credentials: false

    - uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@v7.34.6
      with:
        github_token: ${{ secrets.SEMANTIC_RELEASE }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_TOKEN }}
